### ISSUE TITLE
Got an error on new group variants in tailwind plugin

### ISSUE THREAD

**Issue by ceopaludetto** [fabien-ml/kobalte#101]
**Describe the bug**
The implementation of group and peer variants are incorrect, making postcss crash

**To Reproduce**
1. Intall `@kobalte/tailwindcss` 
2. Try to use any group or peer variant
3. Get this error:

<details>
  <summary>Stack trace</summary>
Error: Expected a pseudo-class or pseudo-element.
    at Root._error (/Users/carlos/Documents/Projetos/Javascript/solid-material/node_modules/.pnpm/postcss-selector-parser@6.0.11/node_modules/postcss-selector-parser/dist/parser.js:174:16)
    at Root.error (/Users/carlos/Documents/Projetos/Javascript/solid-material/node_modules/.pnpm/postcss-selector-parser@6.0.11/node_modules/postcss-selector-parser/dist/selectors/root.js:43:19)
    at Parser.error (/Users/carlos/Documents/Projetos/Javascript/solid-material/node_modules/.pnpm/postcss-selector-parser@6.0.11/node_modules/postcss-selector-parser/dist/parser.js:740:21)
    at Parser.expected (/Users/carlos/Documents/Projetos/Javascript/solid-material/node_modules/.pnpm/postcss-selector-parser@6.0.11/node_modules/postcss-selector-parser/dist/parser.js:1133:19)
    at Parser.pseudo (/Users/carlos/Documents/Projetos/Javascript/solid-material/node_modules/.pnpm/postcss-selector-parser@6.0.11/node_modules/postcss-selector-parser/dist/parser.js:895:19)
    at Parser.parse (/Users/carlos/Documents/Projetos/Javascript/solid-material/node_modules/.pnpm/postcss-selector-parser@6.0.11/node_modules/postcss-selector-parser/dist/parser.js:1084:14)
    at Parser.loop (/Users/carlos/Documents/Projetos/Javascript/solid-material/node_modules/.pnpm/postcss-selector-parser@6.0.11/node_modules/postcss-selector-parser/dist/parser.js:1043:12)
    at new Parser (/Users/carlos/Documents/Projetos/Javascript/solid-material/node_modules/.pnpm/postcss-selector-parser@6.0.11/node_modules/postcss-selector-parser/dist/parser.js:164:10)
    at Processor._root (/Users/carlos/Documents/Projetos/Javascript/solid-material/node_modules/.pnpm/postcss-selector-parser@6.0.11/node_modules/postcss-selector-parser/dist/processor.js:53:18)
    at Processor._runSync (/Users/carlos/Documents/Projetos/Javascript/solid-material/node_modules/.pnpm/postcss-selector-parser@6.0.11/node_modules/postcss-selector-parser/dist/processor.js:100:21)
</details>

**Expected behavior**
Group and peer variants should work

**Additional context**
I think group and peer variants have an unnecessary `:` in declaration. Should be `:merge(.group)[data-${state}] &`

https://github.com/fabien-ml/kobalte/blob/17db58a85daa8cc8508df3317d7e8e6fe0944079/packages/tailwindcss/src/index.js#L35

**Comment by fabien-ml** [comment]
fixed in `v0.4.1` of the tailwind plugin
